// AUTOGENERATED — do not edit by hand.
// Source of truth: packages/server/dbos_argus/protocol.py
// Regenerate via `pnpm run gen:protocol`.

export interface HelloMessage {
  type: "hello";
  server_version: string;
  connection_id: string;
  received_at: string;
}

export interface AppConnectMessage {
  type: "app.connect";
  app_name: string;
  sdk: "python" | "typescript";
  sdk_version: string;
}

export interface PingMessage {
  type: "ping";
  ts: string;
}

export interface PongMessage {
  type: "pong";
  ts: string;
}

export interface ErrorMessage {
  type: "error";
  code: string;
  message: string;
}

export type ServerMessage = HelloMessage | PongMessage | ErrorMessage;
export type ClientMessage = AppConnectMessage | PingMessage;
